name: CI for sample

on:
  push:
    branches:
      - main
    paths:
      - "sample/**"
      - ".github/workflows/sample.yml"
  pull_request:
    branches:
      - main
    paths:
      - "sample/**"
      - ".github/workflows/sample.yml"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample
    steps:
      - uses: actions/checkout@v4

      - name: Install yarn
        run: npm install -g yarn

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "sample/yarn.lock"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Storybook Tests
        run: yarn storybook:ci

      - name: Run Playwright tests
        run: npm run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
